"""create users

Revision ID: fd786dfaf803
Revises: 5468897054e0
Create Date: 2026-01-29 22:51:44.792875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd786dfaf803'
down_revision: Union[str, Sequence[str], None] = '5468897054e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('ADMIN', 'USER', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum = sa.Enum('ADMIN', 'USER', name='role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
